services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: store_db
      POSTGRES_USER: store_user
      POSTGRES_PASSWORD: store_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: bash -lc "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      DJANGO_DEBUG: "1"
      DJANGO_SECRET_KEY: "dev-secret"
      DB_NAME: store_db
      DB_USER: store_user
      DB_PASSWORD: store_pass
      DB_HOST: db
      DB_PORT: "5432"
      TZ: Asia/Tashkent
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
